### PR TITLE
Fixed Flask integration

### PR DESCRIPTION
**Pull request by spollard**
Flask extensions have changed how they are organized. This updates the docs to work with current the current Flask package.

### CODE REVIEW

**Comment by avanov** [comment]
Hmm, interesting. I need to find some spare time to revision CI and Python 2 compatibility.

@spollard @keitheis are you still interested in Python 2 support? I haven't used it since 2015 :)

**Comment by spollard** [comment]
I don't care about python 2 support. I guess we could add try/import statements if we want python 2 to work still? Is the package name the only difference?

**Comment by avanov** [comment]
@spollard I know it's been a while, but I'm happy to merge everything that makes CI happy on Python3 without considering Python2 anymore. if something needs to be done on my side, please do let me know, as I don't remember what was the issue last time I looked at it.

**Comment by spollard** [comment]
I see the CI was last run 2 years ago and there's an error pulling up the logs for python 3.5. Is there a way to force the CI to run again and collect new logs for this commit?

**Comment by avanov** [comment]
There used to be a manual trigger but it's unavailable at this moment, I'll have a look at the CI configuration and the way to re-trigger the job or to run it again for a new branch.

**Comment by avanov** [comment]
@spollard I included this PR into #58 , thanks for your contribution!

**Pull request closed without merging**
